### PR TITLE
Critical emergency pull request

### PR DESCRIPTION
**Pull request by rossjones**
Uppercase format names on search page, was driving me nuts

### CODE REVIEW

**Comment by ntoll** [comment]
OK... I'm not sure what the emergency is. Also, if upper-case is driving you nuts why are you introducing `.upper()`. Surely that's a `.lower()` you want in there..? ;-)

**Comment by rossjones** [comment]
They were mixed, some upper, some lower. Now all upper

**Comment by ntoll** [comment]
Oh, I realise that... I'm just thinking of your mental health here matey... Surely that's LIKE HAVING THE UI SHOUT AT YOU ALL THE TIME!!!!!11!1!!1!! :-)

Totally agree it should be consistent, why not go for the far more chilled out `lower()`..? Think of the amount of stress we'll be reducing as a result.

**Comment by rossjones** [comment]
Lower is too hard to read on that page, Upper just looks better :)

**Pull request merged**
